version: '3.8'

services:
  kafka-kraft:
    image: confluentinc/cp-kafka:7.4.10
    container_name: kafka-kraft
    restart: always
    user: root
    user: root
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    environment:

      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '0@localhost:9094'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'Kivkq2TnS6OC3n0Y13IlyQ'

      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,SSL://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092,SSL://santa-cruz-kafka-0.iainschmitt.com:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,SSL:SSL,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'

      KAFKA_SSL_KEYSTORE_FILENAME: 'server.keystore.jks'
      KAFKA_SSL_KEYSTORE_CREDENTIALS: 'keystore.password'
      KAFKA_SSL_KEY_CREDENTIALS: 'keystore.password'
      KAFKA_SSL_KEY_PASSWORD: 'd1e3d1476afa0ee73239415e984000ce'
      KAFKA_SSL_TRUSTSTORE_FILENAME: 'server.truststore.jks'
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: 'keystore.password'
      KAFKA_SSL_CLIENT_AUTH: 'none'
      KAFKA_SSL_PROTOCOL: 'TLSv1.2'
      KAFKA_SSL_ENABLED_PROTOCOLS: 'TLSv1.2'

      KAFKA_LOG_DIRS: '/var/lib/kafka/data'

      KAFKA_NUM_NETWORK_THREADS: 3
      KAFKA_NUM_IO_THREADS: 8
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 102400
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 102400
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR: 1

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_LOG_RETENTION_HOURS: -1
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

      KAFKA_HEAP_OPTS: "-Xmx256m -Xms256m"
      KAFKA_JVM_PERFORMANCE_OPTS: "-server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent -Djava.awt.headless=true -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport"

      KAFKA_BACKGROUND_THREADS: 2

    volumes:
      - /opt/kafka-data/kafka:/var/lib/kafka/data:Z
      - ./ssl/server:/etc/kafka/secrets:ro,Z
    networks:
      kafka-net:
        ipv4_address: 192.168.111.11
    deploy:
      resources:
        limits:
          memory: 350M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  kafka-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.111.0/24
